"""add swap_session table

Revision ID: 61231e8c87e2
Revises: 8543e0ca4193
Create Date: 2026-10-01 19:18:28.912289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61231e8c87e2'
down_revision = '8543e0ca4193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swap_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swap_request_id', sa.Integer(), nullable=False),
    sa.Column('proposed_by_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['swap_request_id'], ['swap_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('swap_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_swap_session_swap_request_id'), ['swap_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_swap_session_swap_request_id'))

    op.drop_table('swap_session')
    # ### end Alembic commands ###
