"""make password nullable add oauth_provider and oauth_id to user

Revision ID: b4666b7a6c11
Revises: e3576da3e437
Create Date: 2026-10-01 21:06:59.136254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4666b7a6c11'
down_revision = 'e3576da3e437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('oauth_id', sa.String(length=256), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.create_unique_constraint(None, ['oauth_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('oauth_id')
        batch_op.drop_column('oauth_provider')

    # ### end Alembic commands ###
