"""add is_admin and is_active_account to user

Revision ID: e3576da3e437
Revises: 61231e8c87e2
Create Date: 2026-10-01 20:10:58.890832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3576da3e437'
down_revision = '61231e8c87e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin',          sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('is_active_account', sa.Boolean(), nullable=False, server_default='true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active_account')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
