"""add indexes on swap_request and user_skills

Revision ID: f0c6264ef940
Revises: 0608af6ccba0
Create Date: 2026-10-01 17:17:26.482842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c6264ef940'
down_revision = '0608af6ccba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_swap_request_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swap_request_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swap_request_status'), ['status'], unique=False)

    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_skills_skills_id'), ['skills_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_skills_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_skills_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_skills_skills_id'))

    with op.batch_alter_table('swap_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_swap_request_status'))
        batch_op.drop_index(batch_op.f('ix_swap_request_sender_id'))
        batch_op.drop_index(batch_op.f('ix_swap_request_receiver_id'))

    # ### end Alembic commands ###
